#PRODUCTION
nas.root-folder=/storage/pool
#app.cookie-secure=true
#app.sameSite=none

app.registration-open=false

#MySQL Database attachment
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


#This secret key is the cryptographic key used to SIGN tokens.
#Anyone who has the key can generate and validate JWTs.
#
#Requirements:
#- For HS256, must be at least 32 characters.
#- Should come from environment variable in real systems.
# application-prod.properties or .env
# GENERATE A NEW SECRET - Using powershell:
#$b = New-Object byte[] 64; [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($b); [Convert]::ToBase64String($b)
app.jwt-secret=${JWT_SECRET}