#PRODUCTION
nas.root-folder=/storage/pool
#app.cookie-secure=true
#app.sameSite=none

#MySQL Database attachment
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}